### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by kaplun** [gadogado/hn-hired#4]
When there are many entries, and HackerNews break the comments with a "More" link at the bottom, does this script follow them?

It doesn't seem to me at the moment.

**Comment by gadogado** [comment]
hey there @kaplun there's infinite scrolling for *top level* comments only ( job posting ) - none of the child comments or anything under `more` would be included.   does that help?

**Comment by kaplun** [comment]
I am not sure infinite scrolling is there. E.g. for "Who's hiring October 2018" https://news.ycombinator.com/item?id=18113144 I don't see infinite browsing, but a "More" link at the bottom, that leads to the second page.

Our job offer happens to appear on page 4: https://news.ycombinator.com/item?id=18113144&p=4 because we posted quite early.

At the time of our posting, when it was still on page 1, I was able to happily search for it in your awesome service and it was always coming up.

As soon as it was moved to page 2 it stopped appearing.

(for reference our job offer is: https://news.ycombinator.com/item?id=18115979)

**Comment by gadogado** [comment]
Ah ok that really helps!  I'll add something shortly to ensure all of the `more` links are aggregated as well.

**Comment by gadogado** [comment]
@kaplun this should be fixed now.  apologies for the delay - I had some issues w/ aws lambda timing out which took me awhile to figure out 😄 

<img width="1133" alt="screen shot 2018-10-14 at 10 18 17 am" src="https://user-images.githubusercontent.com/34672/46919871-8f3f3e80-cf9a-11e8-958f-0a6d7760a6d8.png">

**Comment by kaplun** [comment]
Super cool! Thanks a lot :tada:
